name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.poetry/bin:$PATH"

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: |
          poetry run python -m unittest tests.unit.test_main
          poetry run python -m unittest tests.unit.helpers.test_helpers
          poetry run python -m unittest tests.unit.models.test_responseModel

  integration_test:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.poetry/bin:$PATH"

      - name: Install dependencies
        run: poetry install

      - name: Run integration tests
        run: |
          pytest tests/integration/test_integration.py
